### ISSUE TITLE
Missing cmd execution

### ISSUE THREAD

**Issue by daZiton** [fhem/fhem-rhasspy#1]
In my opinion the execution of the given comand ist missing in this area.
"$error = AnalyzeCommandChain($hash, $cmd);" or something like that i think

https://github.com/fhem/fhem-rhasspy/blob/b25b262c239eafba72115372ee49a12cb288fd49/FHEM/10_RHASSPY.pm#L1871-L1892

Thanks for your work.

**Comment by drhirn** [comment]
What makes you think so? Is anything not working as expected?

**Comment by daZiton** [comment]
I created the attr rhasspyChannels in a Kodi device 
First I tried it like this: ChannelName=open plugin://plugin.video.twitch/?channel_id=CHANNEL_ID&mode=play
The problem is in this case the command will be split on the ":" (redirect to another device) and i didn't found a way to mask the colon
So i changed the channel parameter to the complete command for the device and set it in "":
ChannelName="set $DEVICE open plugin://plugin.video.twitch/?channel_id=CHANNEL_ID&mode=play"
Now the command seems pretty good in the logfile, but nothing happen.
Log FHEM:
2021.05.23 15:19:11 5: "open plugin://plugin.video.twitch/?channel_id=CHANNEL_ID&mode=play" has quotes...
2021.05.23 15:19:11 5: ...and is now: open plugin://plugin.video.twitch/?channel_id=CHANNEL_ID&mode=play (open plugin://plugin.video.twitch/?channel_id=CHANNEL_ID&mode=play)

**Comment by drhirn** [comment]
https://forum.fhem.de/index.php/topic,119447.msg1158841.html#msg1158841
